project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "EDUC 219: Principles of Teaching Math and Science in Urban Classrooms II"
  description: "Course site for EDUC 219 at Howard University"
  site-url: "https://educ219-fa26.github.io"
  
  repo-url: "https://github.com/professornaite/educ219-fa26/"
  
  open-graph: true

  page-footer:
    right: "This page was built by Nathan N. Alexander, PhD in [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2026, Nathan N. Alexander"
    background: "#ccb6b1"
   
  sidebar:
    logo: "img/carter-g-woodson.jpg"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://professornaite.github.io/educ219-fa26/
        text: "GitHub page"
      - icon: code-square
        href: https://canvas.howard.edu/courses/70108
        text: "Canvas site"
    style: "docked"
    search: true
    collapse-level: 1
    contents:  
    - section: "Course information"
      contents:
        - href: index.qmd
          text: Calendar
        - href: course-overview.qmd
          text: Overview
        - href: assignments.qmd
          text: Assignments
        - href: who.qmd
          text: Site photo
    - section: "Modules"
      contents:
        - href: modules/module00.qmd
          text: Overview
        - href: modules/module01.qmd
          text: Module 1
        - href: modules/module02.qmd
          text: Module 2
        - href: modules/module03.qmd
          text: Module 3
        - href: modules/module04.qmd
          text: Module 4
        - href: modules/module05.qmd
          text: Module 5
        - href: modules/module06.qmd
          text: Module 6
        - href: modules/module07.qmd
          text: Module 7
        - href: modules/module08.qmd
          text: Module 8
    - section: "Rubrics"
      contents:
        - href: other/philosophy.qmd
          text: Philosophy of education
        - href: other/archive.qmd
          text: Historical artifacts
        - href: other/trial.qmd
          text: Trial reenactment
    - section: "Supreme Court Trials"
      contents:
        - href: trials/plessy-ferguson.qmd
          text: Plessy v. Ferguson (1896)
        - href: trials/brown-board.qmd
          text: Brown v. Board (1954)

format:
  html:
    theme:
      light: [spacelab, style/school-house.scss]
      dark: [spacelab, style/school-house.scss, style/theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    callout-appearance: simple
    colorlinks: true
    code-copy: true
    code-overflow: wrap
    toc: true

execute: 
  freeze: auto
    
editor: visual